name: Elixir CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.12.3', '1.13.4', '1.14.2']
        otp: ['24.3', '25.0']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Cache Hex packages
      uses: actions/cache@v3
      with:
        path: ~/.hex
        key: ${{ runner.os }}-hex-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-hex-

    - name: Cache Hex + Rebar build directories
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/elixir
          ~/.cache/rebar
        key: ${{ runner.os }}-elixir-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-elixir-

    - name: Install dependencies
      run: mix deps.get --only test

    - name: Compile the project
      run: mix compile

    - name: Run tests with coverage
      env:
        MIX_ENV: test
      run: |
        mix coveralls.json

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: cover/excoveralls.json

#    - name: Generate coverage badge
#      if: success()
#      run: |
#        curl -s https://codecov.io/bash | bash -s -- -f cover/excoveralls.json
      