name: Elixir CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.18.1']
        otp: ['27.2']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Compile the project
        run: mix compile

      - name: Run tests with JUnit formatter
        env:
          MIX_ENV: test
        run: |
          mkdir -p test_results
          mix test --formatter ExJUnitFormatter --output test_results/junit.xml

      - name: Upload JUnit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: test_results/junit.xml

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cover/excoveralls.json

      - name: Publish Test Results to GitHub Checks
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
            report_paths: test_results/junit.xml
